config/routes.rb
Chat::Application.routes.draw do
  get "users/create"

  root :to => "pages#home"
  devise_for :users
  match "/dashboard" => "chatrooms#index", :as => :user_root

  resources :users, only: [:create] do
    resources :chatrooms
  end

  resources :chatrooms do
    resources :msgs, only: [:create]
    resources :users, only: [:create]
    member do
      get "full"
    end
  end

  resources :msgs, only: [] do
    collection do
      get "fetch"
    end
  end

  resources :suggestions, only: [:index, :create] do
    member do
      put "vote"
    end
  end
end

app/models/chatroom.rb
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
# (c) Rystraum Gamonez

class Chatroom < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :msgs
  has_one  :last_message, class_name: Msg, readonly: true, order: "created_at DESC"

  attr_accessible :topic
end

app/models/msg.rb
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
# (c) Rystraum Gamonez

class Msg < ActiveRecord::Base
  belongs_to :chatroom
  belongs_to :user

  attr_accessible :message

  delegate :id, to: :user, prefix: true, allow_nil: true

  default_scope includes(:chatroom, :user)

  def as_json(options={})
    super.merge({
      created_at_in_iso: created_at_in_iso,
      created_at_in_local: created_at_in_local,
      user: user.as_json
    })
  end

  def created_at_in_local
    return created_at.in_time_zone 8
  end

  def created_at_in_iso
    return created_at.iso8601
  end

  def to_s
    return message
  end
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  attr_accessible :content, :votes
  validates_presence_of :content
  default_scope order("votes desc")
end

app/models/user.rb
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
# (c) Rystraum Gamonez

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :display_name

  has_and_belongs_to_many :chatrooms
  has_many :msgs

  before_validation :default_display_name

private
  def default_display_name
    self.display_name = self.email.split("@").first if self.display_name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user_from_http_basic!
  
  def authenticate_user_from_http_basic!
    if (request.authorization)
      authorization = ActionController::HttpAuthentication::Basic.user_name_and_password(request)
      email = authorization[0]
      password = authorization[1]
    end
    
    user = User.find_for_authentication email: email
    if user && user.valid_password?(password)
      sign_in user, store: false
    end
  end
end

app/controllers/chatrooms_controller.rb
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
# (c) Rystraum Gamonez

class ChatroomsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :user_is_owner, :only => [:edit, :update, :destroy]
  before_filter :user_is_allowed, :only => [:show, :full]

  # GET /chatrooms
  # GET /chatrooms.json
  respond_to :html, :json
  def index
    @chatrooms = current_user.chatrooms.includes(:users).all
    respond_with @chatrooms
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @msgs = @chatroom.msgs.last(20).reverse
    respond_with @chatroom
  end

  def full
    @msgs = @chatroom.msgs.reverse
    respond_with @chatroom
  end

  # GET /chatrooms/new
  # GET /chatrooms/new.json
  def new
    @chatroom = current_user.chatrooms.new
    respond_with @chatroom
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = current_user.chatrooms.build(params[:chatroom])

    respond_to do |format|
      if current_user.chatrooms << @chatroom
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render json: @chatroom, status: :created, location: @chatroom }
      else
        format.html { render action: "new" }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chatrooms/1
  # PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update_attributes(params[:chatroom])
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy

    respond_to do |format|
      format.html { redirect_to chatrooms_url, alert: "Chatroom deleted. :(" }
      format.json { head :ok }
    end
  end

private
  def user_is_owner
    @chatroom = Chatroom.find(params[:id])
    redirect_to root_path, :flash => { :notice => "You don't own that" } unless current_user.chatrooms.include? @chatroom
  end

  def user_is_allowed
    @chatroom = Chatroom.find(params[:id])
    redirect_to root_path, :flash => { :notice => "You don't have permission to see this" } unless @chatroom.users.include? current_user
  end
end

app/controllers/msgs_controller.rb
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
# (c) Rystraum Gamonez

class MsgsController < ApplicationController
  before_filter :authenticate_user!
  
  respond_to :html, :json
  def create
    @chatroom = Chatroom.find params[:chatroom_id]
    @msg      = @chatroom.msgs.build params[:msg]
    @msg.user = current_user
    @msg.save

    respond_to do |format|
      format.html { redirect_to @chatroom }
      format.js { render :nothing => true }
    end
  end

  def fetch
    @msgs = Msg.where "id > ? AND chatroom_id = ?", params[:msg_id], params[:chatroom_id]
    respond_with @msgs
  end
end

app/controllers/pages_controller.rb
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
# (c) Rystraum Gamonez

class PagesController < ApplicationController
  def home
    s = ""; IO.readlines(Rails.root.join("CHANGELOG.md")).each {|l| s += l }
    @changelog = s.truncate(1000)
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < InheritedResources::Base
  respond_to :html, :js

  def create
    create! { suggestions_path }
  end

  def vote
    resource.votes += 1
    if resource.save
      redirect_to suggestions_path, flash: { success: "Thanks for voting!" }
    else
      redirect_to suggestions_path, flash: { error: "OHNO!" }
    end
  end
end

app/controllers/users_controller.rb
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
# (c) Rystraum Gamonez

class UsersController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @user = User.find_by_email(params[:user][:email])

    if @user.nil?
      redirect_to @chatroom, :flash => { :error => "No such user" }
    elsif @chatroom.users.include? @user
      redirect_to @chatroom, :flash => { :error => "User is already in here" }
    else
      @chatroom.users << @user
      redirect_to @chatroom, :flash => { :notice => "User invited" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_chatroom.html.haml
- last_message = chatroom.last_message
.chatroom.panel.pull-left.panel-primary
  .panel-heading
    .panel-title.topic= link_to "#{chatroom.topic.titleize}", chatroom
  = render "msgs/last_message", last_message: last_message if last_message
  
  .users
    with: 
    %ul
      - chatroom.users.each do |u|
        %li= u.email

  .panel-footer
    = link_to "Enter", chatroom, class: "pull-right btn btn-primary"
    .clear

app/views/chatrooms/_form.html.haml
= form_for(@chatroom) do |f|
  - if @chatroom.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chatroom.errors.count, "error")} prohibited this chatroom from being saved:"
      %ul
        - @chatroom.errors.full_messages.each do |msg|
          %li= msg

  = f.label :topic
  = f.text_field :topic

  = f.submit "Submit", class: "btn"

app/views/chatrooms/edit.html.erb
<h1>Editing chatroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/full.html.haml
#chatroom
  %p#notice= notice
  = link_to 'Back', @chatroom

  %p
    %strong Topic
    %span= @chatroom.topic

  %div{style: "margin-bottom: 20px"}
    %strong Members
    = render @chatroom.users

  %div{style: "margin-bottom: 20px"}
    %strong Delete
    I want to
    = link_to "delete", @chatroom, confirm: "You will lose everything in this chatroom. Are you sure?", method: :delete
    this chatroom


  - if @chatroom.users.count > 2
    :css
      #messages-list .other .who { display: inline }
  #current-user{:style => "display:none"}= current_user.email

  %p Messages:
  #messages-list
    = render @msgs

  :javascript
    $(document).ready(function() {
      $(".hidden").show();
    });

app/views/chatrooms/index.html.haml
%h1 Your chatrooms

#chatrooms= render @chatrooms

= link_to 'Create a Chatroom', new_user_chatroom_path(current_user), class: "btn btn-primary"

app/views/chatrooms/new.html.haml
.sign_in
  .round_container
    %h1 New chatroom
    = render 'form'
  .devise_links
    .actions= link_to '< Back to chatrooms', chatrooms_path, class: "button-like"

app/views/chatrooms/show.html.haml
#chatroom-id.none= @chatroom.id
#last-msg-id.none= (not @chatroom.msgs.empty?)? @chatroom.msgs.last.id  : 0
#current-user.none= current_user.email

%ul.actions.nav.nav-pills.nav-justified
  %li= link_to '< Back to chatrooms list', chatrooms_path, class: "button-like"
  %li= link_to 'Invite members', "#", id: "invite", class: "button-like"
  %li= link_to 'Change topic', (edit_chatroom_path(@chatroom) if current_user.chatrooms.include? @chatroom), id: "change-topic", class: "button-like"
  %li{style: "display: none"}= link_to 'Allow Notifications', "#", id: "notification", class: "button-like"
  %li{style: "display: none"}= link_to 'Temporarily disable notifications', "#", id: "toggle-notif", class: "button-like"

%br.clear

#chatroom
  %p#notice= notice

  .topic
    %strong Topic
    %span= @chatroom.topic
  
  #change-topic-form= render 'form'

  .members
    %strong Members
    %br
    = render @chatroom.users
    
  #invite-form
    = form_for [@chatroom, @chatroom.users.new], class: "form-inline" do |f|
      = f.submit "Invite", class: "btn btn-primary btn-small"
      = f.text_field :email

  - if @chatroom.users.count > 2
    :css
      #messages-list .other .who { display: inline }

  = form_for [@chatroom,Msg.new], class: "form-inline" do |f|
    = f.text_area :message, :rows => 1, :tabindex => 1
    = f.submit "Send", :id => "send-message", class: "btn btn-primary"

  %p Latest 20 Messages:
  #messages-list
    = render @msgs

  = link_to "Full message history", full_chatroom_path(@chatroom)

:javascript
  $(document).ready(function() {
    $.timeago.settings.allowFuture = true;
    $("abbr.timeago").timeago();
    $("#change-topic-form").hide();
    $("#change-topic").click(function(e){
      e.preventDefault();
      $("div.topic").slideToggle();
      $("#change-topic-form").slideToggle();
      return false;
    });

    $("#invite-form").hide();
    $("#invite").click(function(e){
      e.preventDefault();
      $("#invite-form").slideToggle();
      return false;
    });
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Chat
    %meta{ name: "viewport", content: "width=device-width, inital-scale=1.0"}
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{href: 'http://fonts.googleapis.com/css?family=PT+Sans', rel: 'stylesheet', type: 'text/css'}
  
  %body
    #topmenu
      .container= render "shared/topmenu"

    #wrap
      #main.container
        .row
          .col-lg-12
            = render "shared/messages"
            = yield

    #footer
      .container= render "shared/footer"

  = render "shared/analytics"

app/views/msgs/_last_message.html.haml
.last_message
  %blockquote.pull-right
    %p= last_message
    %small
      %cite{title: "#{last_message.user.display_name}"}= last_message.user.display_name
      %strong #{distance_of_time_in_words last_message.created_at_in_local, Time.now} ago

.clear

app/views/msgs/_msg.html.haml
%div{class: "#{'mine' if msg.user == current_user} #{'other' unless msg.user == current_user}"}
  %dl.msg
    %dt.what
      %span.who= (msg.user.display_name.blank? ? msg.user.email.split("@").first : msg.user.display_name ) + ":"
      = msg.message
    %dd.when
      %abbr.timeago{:title => msg.created_at_in_iso}= msg.created_at_in_local
      .hidden{style: "display: none"} #{distance_of_time_in_words msg.created_at, Time.now} ago

app/views/msgs/create.html.erb
<h1>Msgs#create</h1>
<p>Find me in app/views/msgs/create.html.erb</p>
<%= debug @msg %>

app/views/pages/home.html.haml
%div{style: "text-align: center"}
  = image_tag "chatmonkey.png", style: "max-height: 300px"

:markdown
  #{@changelog}

app/views/shared/_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29314231-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_footer.html.haml
.row
  .col-lg-4
    %h1 Site links
    %ul
      %li= link_to "Suggestions list", suggestions_path

  .col-lg-4
    %h1 Credits!
    %ul
      %li= link_to "Chatmonkey Logo by Iris Gem Li", "http://februarism.com", target: :_new
      %li= link_to "Banana Icon by Dimpoart of Indeepop", "http://www.iconspedia.com/icon/yammi-banana-716.html", target: :_new
      %li= link_to "Monkey 'Like' Hand by MailChimp®", "http://www.flickr.com/photos/freddievonchimp/4774020533/", target: :_new

  .col-lg-4
    = render "suggestions/form"

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  = content_tag(:div, :class => "flash #{key} alert") do
    %button{type: "button", class: "close", data: { dismiss: "alert" }} &times;
    = value

app/views/shared/_topmenu.html.haml
.navbar
  = link_to root_path, class: "navbar-brand" do
    = image_tag "chatmonkey_logo.png"
    %span= Rails.application.config.chatmonkey_version

  %ul.nav.navbar-nav.pull-right
    - if user_signed_in?
      %li= link_to "Chatrooms", user_root_path
      %li= link_to current_user.email + " (#{current_user.display_name})", edit_user_registration_path
      %li= link_to 'Logout', destroy_user_session_path, :method => :delete
    - else
      %li= link_to "Sign up", new_user_registration_path
      %li= link_to "Log in", new_user_session_path

.clear

app/views/suggestions/_form.html.haml
.ajax_callback
- if user_signed_in?
  = form_for Suggestion.new, remote: true do |f|
    = f.label "Any new ideas or suggestions?"
    = f.text_area :content, id: "suggestion-content"
    = f.submit "WANT!", id: "submit-suggestion"
  = link_to "More ideas?", "#suggestion-content", id: "show-suggestion-form", style:"display:none"

  :javascript
    function create_flash(msg, classes) {
      $(".ajax_callback > *").stop().fadeOut();
      dom = $("<div></div>").addClass("flash " + classes).html(msg).hide();
      $(".ajax_callback").empty().append(dom);
      $(".ajax_callback > *").stop().fadeIn();
      $("#new_suggestion").hide();
      $("#show-suggestion-form").show();
    }

    $(document).ready(function(){
      $("#suggestion-content").autoResize();
      $("#show-suggestion-form").click(function(e){
        e.preventDefault();
        $(".ajax_callback > *").hide();
        $("#new_suggestion").slideDown();
        $(this).hide();
        return false;
      });

      $("#new_suggestion")
        .bind('ajax:loading', function() {create_flash("Submitting..","alert");})
        .bind('ajax:success', function(e, data, status, xhr) {create_flash("Thanks!","success"); $("#suggestion-content").html("");})
        .bind('ajax:failure', function(e, xhr, status, error) {create_flash("OHNO! Something happened! Can you try again?","error");});
    });

app/views/suggestions/index.html.haml
%h1 Existing suggestions

.grid_16
  - collection.in_groups_of(5,false).each_with_index do |group,gi|
    %div{class: "grid_8 #{'alpha' if gi%2 == 0} #{'omega' if gi%2 == 1}"}
      %table{style:"width: 100%; margin-bottom: 0"}
        - group.each do |suggestion|
          %tr
            %td{style:"width: 70%"}= suggestion.content
            %td{style:"width: 10% display: table-cell; vertical-align: middle;"}= suggestion.votes
            %td{style:"width: 20%; display: table-cell; vertical-align: middle;"}
              = form_for suggestion, url: vote_suggestion_path(suggestion), method: :put do |f|
                = f.hidden_field :suggestion_id, value: suggestion.id
                = f.submit "Want!", class: "link want"
  .clear

app/views/users/_user.html.haml
%span{class: "#{!current_user.blank? and current_user.email == user.email ? 'me': 'notme'}", style: "margin: 0 5px"}
  = user.email
  = "[#{user.display_name}]"
  = "(Me!)" if !current_user.blank? and current_user.email == user.email

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>